### ISSUE TITLE
Switching profiles by events doesn't run shortcuts

### ISSUE THREAD

**Issue by Forever-Young** [henrichg/PhoneProfilesPlus#10] opened 2016-10-12 08:13 UTC
I tried manual switching, it works, automatic switching - it doesn't, nothing in receiver's logs (I invoke shortcuts for Automagic tasks)

**Comment by henrichg** [comment] 2016-10-12 14:25
Fixed in this beta: https://docs.google.com/uc?id=0B5RwcWvhmm8RN3k0bDEtZzRXN2M&export=download
#

**Comment by Forever-Young** [comment] 2016-10-12 14:59
Thank you, it works, but it doesn't work in one last place - when profile is activated when I restart events.

**Comment by henrichg** [comment] 2016-10-12 15:21
In restart events, allications and shortcuts are not started. This is by design. It is not OK?

**Comment by Forever-Young** [comment] 2016-10-12 15:46
But why?
My usage for this option is enable/disable notifications for pebble watch?
Maybe option for that?

**Comment by henrichg** [comment] 2016-10-12 17:37
This version starts applications and shortcuts from restarts events, but only when you restarts from Activator, Editor, notification. Not if event has "End of event"-"And do"="Restart events" and profile has "After duration do"="Restart events".

https://docs.google.com/uc?id=0B5RwcWvhmm8RN3k0bDEtZzRXN2M&export=download

**Comment by Forever-Young** [comment] 2016-10-12 17:41
Perfect, thank you very much.

**Comment by Forever-Young** [comment] 2016-10-23 17:57
Will latest upcoming version 'Restart' by tasker feature run shortcuts?
(I tried action '......RESTART_EVENTS' with extra 'unlock_events_run' = true in current version, it restarts events, but doesn't run shortcuts from profiles)

**Comment by henrichg** [comment] 2016-10-23 18:44
In latest release version is not posible to restart events. But I added this support. 
Install this: https://docs.google.com/uc?id=0B5RwcWvhmm8RN3k0bDEtZzRXN2M&export=download)

Look in Editor at "Important infos". In end of section Profile is writed new method how to activate profile and in end of section Events is writed how to manage events.

**Comment by Forever-Young** [comment] 2016-10-25 18:51
Thank you very much

**Closed** 2016-10-26 11:59 UTC
